[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "14d0db018b87b9baf860447d85bbecbb6d9551c5855ca957d492e39467d388c3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "14d0db018b87b9baf860447d85bbecbb6d9551c5855ca957d492e39467d388c3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "213c2e177382908431d7e428d3c323316c647e4f0241fbd5aa28907e74ad3538"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "213c2e177382908431d7e428d3c323316c647e4f0241fbd5aa28907e74ad3538"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "681c4d011177353425121ca40297f57580ae6ce50acddcf301d657d6ef04bd71"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "powerpc64le"
git-tree-sha1 = "608902a3980fcc42b8c3c0de2b59e6f6991fa681"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "5ae56401e046b9d0a7983e3414ec95affa8ebff95fe5c0bb2af56011135fd613"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "14d0db018b87b9baf860447d85bbecbb6d9551c5855ca957d492e39467d388c3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "14d0db018b87b9baf860447d85bbecbb6d9551c5855ca957d492e39467d388c3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "213c2e177382908431d7e428d3c323316c647e4f0241fbd5aa28907e74ad3538"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "213c2e177382908431d7e428d3c323316c647e4f0241fbd5aa28907e74ad3538"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "681c4d011177353425121ca40297f57580ae6ce50acddcf301d657d6ef04bd71"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "46c2f352ea1d158a976b8ebcb28005a21d246ee4"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "973ccae52aa9399fc287b0b0363b2d9db7b88c003115fe88ccb02de75617254f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "3bfdc584182a6437e58b70da36cb7c86552cfde7"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "202e6d3b8949d43b125b5bc64421fd45df7fc62852060367820ef223ad4b8500"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "58a6ba04a2abae1b7ff20b0d219b8e7af2fd6507"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "5ed6ea7ad9ec069491b4e41917965b58086cff4cb2bd8db032dae45935a1b74f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63f62a7d5451e8cec438a351f17957055446e6da"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "fa599413bbf91011d5ccf909edefa31a9481bec9bccef4c4d89d9ff582b1850a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "cad425344fddcf87808c079505f3142e52817f2c"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "cb07f2246a6ed8ea94778b84c86d7cee2804055e136ee2d9ae60489af46fd832"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "52506eec9a5d5f815efc201393ae51807265da5f"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "e0bf06f69b92a25557952e7634d77ceeba170d730ae690a25adcb0df86ff0a77"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "511004ed0d4146f2aa48728cf61a02740cde66cc"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "9573c7ce47d82d4dd3eec92177fa47c4553085732d094fb424fde531b9124d31"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "9dafa58b8c0a607d64f0d639225caa982609b437"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "88118d51ca80d30bcacb84a673337e0452906531a1c13575e966f1efefee118c"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df9a0a42154ab2b6a63661166d3e66dfa28315d0"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "c742485e87ad570944b11571173f34ca9abe85f85fca87a3f7a8cba6aaf1c584"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d33c0b2ff22e322887f1e406149a36510e46a0e5"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "548b1b6a97cb7d99c6769a86da2e74e1a4c852b87dd7a3325f4e0512a52c2a95"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "f3346c41bcd354bae1ad277e7ab8a3b44ee6f2cb"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "ce5f2595147db2d4a2b2ff3f0b0c8c41dd2bc0f0bc12a926366377ff9cb58c50"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fdf84bf2effb1353a620a1795e939fd9e6bf34d0"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "3a6a5a480efdd56e795b12df5ca5a74dd09575264520870e1ea025d3a0d2daba"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "72e9b62fae869dcfac650564e4f513babd43a37e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "8a1e95f15cb76546d95ceda29018a0bf5de077675944d8444f670a76a9a7a80d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bdfaa07b683008c0dcf2617eac84a035789ad4d6"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "16c316771c1813d226b19ba9522b5ff1386eeec5ed8cefc172d7bd07356bea9c"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee7dc262d32208aa8a484bd2e6f42d75ed9d0900"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "4d849766be5bb5389a81a3fc89ef5aba82700eec3611cd3231bb66019a71997f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "c8f321fb487236a07ba2360bf59c539034ee3271"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "d87ddb2bca3e24ae90717b11aacf9f37488ae853373ddabc3a05f48917a0e8e6"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "36adf31434bc6cd9cacf720fb60ee4f8008e07d6"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "c2d2476361f16663c3cf3e98ba920a32e1f88ffbf24212e0b6f4a58e9a4a2303"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fd9994210aada107c25599f3be8d8d3eb5765dfd"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "11435bc1c653bc02fa34e25ff22301ff72842f37c68e7374ce418eeb276bd9bc"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "e70d78a0ec34d77760cf19303667115d54d8899b"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "e0eedfa98654d3aa040ffce44cc28644e7bad0bb9845fce88593703daa189983"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec87e2b0fda4a228724761a9aa3a81db84a5f604"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "0f96c8bcee215812353c16eadc92b2769ed6035fe887c845ee05c8d6fcc2a720"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "752be6acfd795fd7d4e49f7732f7d8c3b1a7ea34"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "1cb6eb765f0869bd3e739b2d04eb0be9bcc2b4386d1e11b81882674a65032af9"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "ddf8618430c8583f9b276d5e026be16831bdb1fc"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "c6ddc6d7c1e54a0fa42951bccb8b5d09d701c01d578bf435fba21592672fbadd"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-musl.tar.gz"
