[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "6a5d08e46f470bffbc8d24d187d7c76c65004bb2"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "06ab3e82bce8e21bd5b04d85c02e8514700b2173e64974fb1c765b03aee2bc2f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+aarch64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "f540660174357a8220c7c44147ddd226684d00bc"
libc = "musl"
os = "linux"
target_arch = "i686"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6bbf7e61d6f06eb3139d055cd7636f2a4868231446179912afac9a488c7075d3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+i686.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "83c3ab34ac8537543c587616cbbd12e0f3e08fb5"
libc = "musl"
os = "linux"
target_arch = "powerpc64le"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "b0efcfc67b9f66e7844a9c2113033cc1858618779e15ddfa3a063027b1311d95"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+powerpc64le.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "b2229c7f8d05ec9fba9fd5c8326728326c408a7c"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "ec838fb194cbef13a2fd7e058cfd571fa71c117b344c5696c7daf1f84951be4f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+x86_64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "7f902e19303fd68baaf4209e82d827a05836ddf7"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "b12d489dc2db3aa204c4c9c08e9fc0556922b8fb711ab2d05a979f1fbfc73750"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "3a190a29005b263255454325b5cdda2a67c5b0c6"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "f7af25109293b215ae32f10762d3f36b3ca35336af4c4ea5d9e0c1078613becc"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
