[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1c3baadefaae3808aba26c7821ccff49860911f677efb6f9569ee2966fbea4f3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1c3baadefaae3808aba26c7821ccff49860911f677efb6f9569ee2966fbea4f3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9a774aa82138fab806003dbbbd8c0097016aad345a850b68e4d4a827b7575e76"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9a774aa82138fab806003dbbbd8c0097016aad345a850b68e4d4a827b7575e76"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "55c6c87594221a0a7d9f0cbf7d9ce4c888415cdd364a374b55a6a38f9cea7571"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "powerpc64le"
git-tree-sha1 = "608902a3980fcc42b8c3c0de2b59e6f6991fa681"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6b44d7f4027c06101c073f67fa8f20cdb6477f5797f2117e71f1b8713fdb573c"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1c3baadefaae3808aba26c7821ccff49860911f677efb6f9569ee2966fbea4f3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1c3baadefaae3808aba26c7821ccff49860911f677efb6f9569ee2966fbea4f3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9a774aa82138fab806003dbbbd8c0097016aad345a850b68e4d4a827b7575e76"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9a774aa82138fab806003dbbbd8c0097016aad345a850b68e4d4a827b7575e76"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "55c6c87594221a0a7d9f0cbf7d9ce4c888415cdd364a374b55a6a38f9cea7571"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "560c49b80154416c0f71d107a9f01327c6e5e89a"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "f7417d7677b1c632a7cddf40e86020ccb247867390d60d87cddf18a46d0f2306"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "5339e8f852a5343501c9608d2742c250969e30b8"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "c769cc2f8e883e99cd791ced3a2931379a5af20f91015ef67d9247fece2fa23d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a9ea8df793619c1ccd2dfd369ee1733a361c4b6"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "6b0a2b8c72e66b2e8d0e309c74f124f1869ea25176760a7832d54c4821783036"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5b889f10638e582a7d6643cbdb8c3464b271eef5"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "5d6bed0d3ae87c046cedc79b3b79975fbee57b1aa5c61f11a1052172f6f6df8a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "211d2bda6ed2f722c1c192b00b2089b7a058013e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "96f3cd4b4c2986d99aa4151507f156a4c2ba5c199a578cfbd7a7e73029fc42c4"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "035c535ac9613301b96aa55496126c4998ff86e3"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "c146a8444206e97d867f85eac779f1c2b573f47fbf2603310e1abf808eea279d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "55480f022f2dabebf76e645c529de68b18a6923a"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "4df2fcebc64fa901569ba462f746e88afe913093683758c4f6ff5fe26ac9ec04"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "fc5875003ca08b0cc379c5699c26afcb448c80ee"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "dca146338eac58b5259ea8a115fd301335c30a5578ff54eeb3099b5b6cba1eb6"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "01bf41c320b932291cb84b3dc4a0e1a4e414ad53"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "999090019ae5cbbfd931fd2ecabbd8a42af7fb805078db463bb765cdf3e16349"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7382069215f2e74fc89826387bbaa52b0ed893d3"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "6514f469f6fa851936b00dc860c50c59ef14ddb6bb85fc12ffe7c883ccdaade2"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "2f5f1edb621b414efe0ff24c7470aad4468efdac"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "119b5ed916e053660cd370b52cf9e25367ff045f7dcdde69f72b8c210146b281"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1d3c4eb174dcee0c1b0c41467fbab1db00328ad7"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "2140fc50bd31ea163cf7483bfc47bdf8f002a3e1d01dcf348de67b80fc927b2d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "1c22b8b9d0c308b8e9437b05bd2036c096111073"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "c3b46309b87ebaa8c0e03e99652ab45d2ecbadeb9339936d99420f19669907dd"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "546ed9266b0f2afb2651503165cd1d2c41a9a4e2"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "aa915dd6d67596dc003b9339dc1b5ef153c07e2a4719b88501133d8075ee7e9a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7efd8a9a30990987f7fb22a15da27dda11f995f0"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "88d55cc21058e8d2cc406cd79403fdb58b68bb32e1b06bdd2029811ae4593b15"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "a0aed143e3d4257a99972bd86dacd6c0022e45d5"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "76d0be704aa9f438e65eb5528a216093386f51959eb878567eb4a9b7ca2fd4fb"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "7b52613b14e94ebfaf48228824239196fe32fdb8"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "de08818de0227f81fa66ea364a230c3327f3008a3bac7e5906d509d6ad04aed4"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "998a0d3b93052718b6a0876ba86618b033ee1fc3"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "f18ad30a7f1cc190931b414ff50f6a07915e5dd318d7f90d13378292fa15f991"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "2b11380af613cb552b16993b01a130f7db9c4daa"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "19dcf16b63fb72bfaa2f573c657b28ac09148a9f672447d872d9ef00ddb2f433"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3150586f2c9fc6933928bab4595485904679c8cc"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "8513897b826cadb8f2366e1ce8e53f430a388eba880d758ba3b0ab9ffe80327d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9198b583cbdefa2ca9b7bcdbcfd5519acef5a3e"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "6586cff55b74da5efcdd64cf01fc35bc8c60017e47fa2870c3e6a77fc9bc6767"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "e230df16e83472809dfce4550c726aa76f8f65fe"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "6d4eb4c9f54fb694dce0e13ee8e9173563ca75aacecb80718dcb4636258739b2"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-musl.tar.gz"
