[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "ae68ce1ff9af57563212e72e89edfe33545349bfefb646c756dd458f6dd09c63"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "ae68ce1ff9af57563212e72e89edfe33545349bfefb646c756dd458f6dd09c63"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6249b2a9bdb5bb348566ac66b0ad89192d90e46a4b8a4ab340f87f6da4109207"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6249b2a9bdb5bb348566ac66b0ad89192d90e46a4b8a4ab340f87f6da4109207"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "c6ce40b1531cd8bdc1b1dddd9b0b1fa4b98b7ec0553533f3032fef95c830d4a1"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "powerpc64le"
git-tree-sha1 = "608902a3980fcc42b8c3c0de2b59e6f6991fa681"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "b0f5c62b2d05addd7e6ce1ec8c30c3a7ca4014cf4c2f7a703138cbb82b85c798"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "ae68ce1ff9af57563212e72e89edfe33545349bfefb646c756dd458f6dd09c63"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "ae68ce1ff9af57563212e72e89edfe33545349bfefb646c756dd458f6dd09c63"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6249b2a9bdb5bb348566ac66b0ad89192d90e46a4b8a4ab340f87f6da4109207"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6249b2a9bdb5bb348566ac66b0ad89192d90e46a4b8a4ab340f87f6da4109207"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "c6ce40b1531cd8bdc1b1dddd9b0b1fa4b98b7ec0553533f3032fef95c830d4a1"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "40c0aa5b8f5090de0d8c8a83f060c8d6df27b516"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "7c7cafd8c42159bcb508fde952827966d772b8d7ef0e6f8047d20199ef7fc480"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "8daf2cc79beeb4b5e76f3e2decf4a425a2aa34da"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "580f9f6da6d789e1f1c991527806854a86e7c3f65e761baf4ca1331e31df8ded"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17a2cbe0b61af234ff24383f0f15d9aef6003639"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "3d2d0c9dfb3d7632772044dd0d774fd482a487f5c6a21f2d3a871587d2293648"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9628bb6b66ca27db8179b96f59e9ab6affb2954b"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "716e54e661ed96f8b6c30f7659c9a45c750093b88781b2984e2b75bf201dbf2d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "88f6edee3eaa628ef08d2363720601153831dcad"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "af4e4147ef058c54136fe228d1943409612d3fc43c69f5212c45772d6ba18c1f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "fbb0ff50057e3f1ede2118d35f2c249e4bec858b"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "792cd1da17df9e3466f532624e3b3274e532948fc3d4312393b118e49348921d"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "52a0565eda6e9bd71aaa439de7343f0846d40ea5"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "e7a06b27e0b5bbc48f7aa22d65092bd154f6f033463241fd2b67e7a332968f5e"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "4eaefdcef33ee42ba17c42a9b9e603bd3e5c31ee"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "56ca41910dc1004fe0dbb1157523fe844dc1d378ba17ce470dac931f3fc2328b"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "249222e5208bde09ff55c40bacb35967ea809755"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "e38f3bba12db8a55f99c729f0f078659c253c3cbaabe868514710d8e41587073"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5c1251845722a4ab1c0c05ed12e31213238a5c6"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "b49cc71ba5adf1da99cf5b014578659d39978257d41615abfec0a9e4f79ffdfd"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "9808242eaa5631914a6daf1900358a6b92e07443"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "06ab121d0cfe0c5c383529e842ac2629e4e33a44be4baa1a8902713adf400142"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "dbca9de6ea805deaec5444604d52e5450f18c16e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "5df783fe89e7d771ce32eb78f3cf2fc3f951eace4b6ad4069cb4c82bf8d9f0fb"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "cc456dfb84a545008d8f9588ad7c8513fc4fd3aa"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "d92c2a324ed89616ad6639cc47292d4ff8ce9ca0986dbf9686b9451e77246e22"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3df4eb717fd26546262ea10137a0519f63e5a25"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "0d72aba9a11e57a77171d6327749fca00184cb4bfcc9ece50de183b293a6dc20"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e392afc328c40db2f88cba35c9c930e73dde7783"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "4d19034573ed6b22d439c9c548f599051ec25dad6e70f479ff73eb17fb90d887"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "44f5d0addd78957af466c5542e112b2aca694b54"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "dc1b5bae36da919b9142a97c221a6a6a2acfc80a7a5fb6182300425c3894e44a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "a755a30db0958a53f838f232a408500f78f93101"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "817e75225499fc004adb60d458b68ec1f0f8cc44533ef820790266145776e696"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "493eedf759ec421178ae9590d671161a6e702b7b"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "131bd8313481aa5b5ebc2c56b35f18c3bdc6bacfef37f00a2107c911ab711956"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "4b55236528e12d36b69a561b6a136186af1dd198"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "d32aefac08cf8a39a831b99c0ded21b819aea3975aad7d2ad609dfd948df3b10"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "38d2028dec92f40c4d6bf2842d33fdfa171aeb9a"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "6ed7efff5a4aba5938f529c9d28fe51c082e6c61bd543281b03ab8cf1c9f5b9a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8af221798d7669318a13a08af9cfb52d84bcab36"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "232a3db3845af44d43c17d04c8dac3134c09b092b028acc697c179817c4ca663"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "60e992b2c8de6b2f5981b49b00f60e2a7ebc7636"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "a5867577e40e9f9b73ee5c49da3d23a479e50a2114e814bb8810f39b1436274c"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-musl.tar.gz"
