[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "08da6dd43d85feac0f49c8d2f72ae1d1ea608f078c56035577238130b4ffdaa5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "08da6dd43d85feac0f49c8d2f72ae1d1ea608f078c56035577238130b4ffdaa5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1a91726dd2ee3534ebcfb7a304f74cd4b169b548b396018c0814d0f37fe8ed7a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1a91726dd2ee3534ebcfb7a304f74cd4b169b548b396018c0814d0f37fe8ed7a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9413af42d7b32e07eff00ccdae30166a16e83ebcf57ae0563fb7c905e24160d2"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "powerpc64le"
git-tree-sha1 = "608902a3980fcc42b8c3c0de2b59e6f6991fa681"
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "6add3cf3fe4a2f2e48a2d2f4d3aea563634c1fd325653a0e48e6947c792952ec"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "08da6dd43d85feac0f49c8d2f72ae1d1ea608f078c56035577238130b4ffdaa5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "i686"
git-tree-sha1 = "d1931c87f8b125082bf62e26afda07ada182526b"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "08da6dd43d85feac0f49c8d2f72ae1d1ea608f078c56035577238130b4ffdaa5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1a91726dd2ee3534ebcfb7a304f74cd4b169b548b396018c0814d0f37fe8ed7a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11985d052b17aac422c79870b27f35b321f35bc1"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1a91726dd2ee3534ebcfb7a304f74cd4b169b548b396018c0814d0f37fe8ed7a"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders]]
arch = "aarch64"
git-tree-sha1 = "e09615da5544ab54695942c9d97c90355ed006c2"
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "9413af42d7b32e07eff00ccdae30166a16e83ebcf57ae0563fb7c905e24160d2"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "819bd134f8fd0e9523f57578a8dd94f9ea8833d5"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "db38cfd0adc294bb9dabf605091ef51df90756fb7ba7d73ef5e3b20fcaf3a896"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "f05360b19e3618cec6864f9a4c5483c31f11248e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "9edd44e77d3f8707bb72d1287e556de6fff9d9be6679422fcd636f3f572fc8f1"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e8da567c56cfef3e1c1910b956d4a4fb52ec21e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "be3242ed7161ef0744bc929da9fa56f3e7945644444139798e6878461b559ea0"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c55c830e5eb671e74490d5b482b00713c760226f"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "7778679e3ca5442d6300ab139e8a6bfec2f283653ce922d902b7e90e36cfa1f3"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "4852053a5ad6d6aa6181a3b71633bc3976cb2bec"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "d600f3730880b62b4323a970036ae225dc18a421f0aa22d989916bf4fa79f651"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "powerpc64le"
git-tree-sha1 = "c54f87adab0cdfae3346243ed395c065675edd1d"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "2e5db7df62cd00928056c4fc2dca42e7347ef42966cec485343321a5edf3c050"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "x86_64"
git-tree-sha1 = "2cab29565c2bf1b5663da925bb7c188e7b6716e1"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "1aa55334072133dc11d4e47b6605d458cbabb15c675e850bcb0bdcea4069d0f8"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "i686"
git-tree-sha1 = "792ca6a0f1603e2098b8394dcc1319a05d7f908e"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "6acd4ec00a0bdd2ff80359cceb6fdf273a14fdd3a46d057fb00e2d08bfdfbcfd"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "261303f265a782fa5e54b0ae0c5d297032f25287"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "94cbc578d54136581eea59815d769783048e8385a49e376ab785006cf28d2846"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c0ab1e5be22306b1c32ac0820323eeae4f8da4e3"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "b6071585eba50ce7df0efc15e4ae13698d20c001f463147873dedf2c2888d055"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-build_log]]
arch = "aarch64"
git-tree-sha1 = "2c54d61439e2b9a8397b281c877b209c33a40da2"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-build_log.download]]
    sha256 = "6d4b2c6d1a3e9bc24fbe5495555363896c50a4723fde71e337bec49cc7e77282"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-musl.tar.gz"

[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b19f3fbc885a28b9d6b960f9a506dd6e1722488f"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "5c5ad5c81edadba633e9deeb5d9dc5212c9b391007c6ac2f0000b138adc7a3b5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "0b3a2d7cde8cbf558114373d24476aa4db31d297"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "94c30b7749280f815140b4e9bf2bbd2f5b91cfcfec20e988c58bbd40851da01b"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb98f51dd5b5ee906d5479027e4aedd2e8abb4bb"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "c81acbdd8d0cd9d6c85a3ed538046d0a916e54943361e92fd21d85c893c8101f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "713f0dbadd50e42d3fed35d4f6327afc156b1769"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "ec413f37d37e733c209c0230fc42df3715941205905479826063e63f1d631be0"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "50dd758dc74844c87106e4da02de260b6baac615"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "874dd273f6f16bec4bed4d8140db15674f39715e7079c25e80f3a1d1fb8fdcbf"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "powerpc64le"
git-tree-sha1 = "845b0ea7de5a9a780aeb45ac11fb357ab06fdd4e"
lazy = true
libc = "glibc"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "5b84ca4767adf1e9bd3b8a4ea2ad06722394271ff10ed48657eab05b72cf7ef6"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f6bafb7ef2053ef55c1f7cdca4163c2c0fef766e"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "42b5c56947e2fc7195b55023a8d90a404dc867806815dbc3b02260072d232407"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "i686"
git-tree-sha1 = "380d92348d1f474d21f1e11eccf8d281924a061a"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "5460d8359cd2b005e25045c4cc7d08dc500d9c4160c114a7b44c8c3767c80ac5"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-musl.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "090312c725df22c4f6e19cc19c910c85a7047ffd"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "5ac286e84d7f393e24051c23680a83e2002bedcbdc4eb23d072d7e528f6fad7e"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4aa94eb719641ec10f424444e2bb171f50dccaba"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "f06106e82570d9a6129b62e8ec1926d2dbcb63d3aa6b9e790cbb8f32f61c965e"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-musleabihf.tar.gz"
[[LinuxKernelHeaders-extract_log]]
arch = "aarch64"
git-tree-sha1 = "01e52df350eaec8977e5870cec4743a2b7b3ca9d"
lazy = true
libc = "musl"
os = "linux"

    [[LinuxKernelHeaders-extract_log.download]]
    sha256 = "67447767b59ffa7738683dfd87213f93cf81e4a4548efd683e2c392deb14dd6f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCCBootstrap-x86_64-linux-gnu/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-musl.tar.gz"
