[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "cf072c82e3edfe8ca566df788edf2b22734bf76f"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "66810c3b797d83ff7df7b10a2b6fd765ca3edb2ad692fbd0a02d7ff7d31e3a37"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+aarch64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "0912e0aa68e2615bd65d5c18b4aeb4fba1cfdf24"
libc = "musl"
os = "linux"
target_arch = "i686"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "0002f90d689b9e27c6031639175b73d295bf898a9ebe8dfc6ccf227678aa1e79"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+i686.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "e9132838d792ec188b77faa88316a09c957a8df4"
libc = "musl"
os = "linux"
target_arch = "powerpc64le"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "038337a2e6b78b5e30d2264605f68d61602901a1c64bb65aa94050e7964e2d94"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+powerpc64le.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "121ef43d3ba9300067bcf8c3ce5003ca1567b051"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "18ea877a17f6aa7caa02042fcd94913534f480737e3ce9728c8a1b00a8d3973f"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+x86_64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "8f9b39164c34aa52c58996531bf82d83842c8e9f"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "7ab45c775be9c1fbfd7291d80793785f23e9a8878c928db02006d4902c086954"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "676c8ddda633ca90e6b6570923878d44374f385d"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "39b60890ba13c90c876a739cfa6badf11042231deeb8dc92bf10141cb52835bb"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
