[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "dbb2017aee7e68b8d7940007f4ab966106828a87"
libc = "musl"
os = "linux"
target_arch = "aarch64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1f5da1236f213a2de1a739e9cd24069f3e3281d0da5d8e22b0de2c1d1a6f1edc"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+aarch64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "4f46c87add28c614ea170e9822a6744fc72d0781"
libc = "musl"
os = "linux"
target_arch = "i686"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "cd636de2ca235672a3541742342ba7f523c4adfefbb7a79b7c08b4f3aa204433"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+i686.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "eb50d5699207becb51e239d21d9dfd5ade539803"
libc = "musl"
os = "linux"
target_arch = "powerpc64le"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "80a605f434a5038dbe3723e5c49bd985d5fcea981b0a2d73c78500840535e37e"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+powerpc64le.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "f830b5636d8bac1c8ca619306f41f8a48a702e57"
libc = "musl"
os = "linux"
target_arch = "x86_64"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "d82fc37a74212b662dd9e39da4a401e4589d4668394b683d5d13cb9b36c54be1"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_arch+x86_64.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "a2243c4f39e4b89a3069883a82153e9757ef02c7"
libc = "musl"
os = "linux"
target_arch = "armv6l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "1fe39a8eab5d42a45b08fbe656e55c07b5019430aa6de68653f479f6e95cbb50"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv6l.tar.gz"
[[LinuxKernelHeaders]]
arch = "x86_64"
git-tree-sha1 = "4ea51ba3e7c1b0f5aeb85cde33286b18e3c28f67"
libc = "musl"
os = "linux"
target_arch = "armv7l"
target_call_abi = "eabihf"
target_os = "linux"

    [[LinuxKernelHeaders.download]]
    sha256 = "a4eba325ae8ca36d52fbe7508b57f66d9b19d2621f00d8312b2bdf1b985c64a6"
    url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/LinuxKernelHeaders-v5.15.14+1/LinuxKernelHeaders.v5.15.14.x86_64-linux-musl-target_os+linux-target_call_abi+eabihf-target_arch+armv7l.tar.gz"
