name = "LinuxKernelHeaders"
version = "6.9.0"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "LinuxKernelHeaders"
platform = "x86_64-linux-gnu"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:0e762a71dad379b96e13c5bc9136056ba9126f20"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:df73eb334d70ce81cb2df4f17e96a6b7ec8e58d23c9b14d862dd40e46726c55f"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4ded0f2d2e5efe3985ac688dc7feb8f6b9bbf8f6"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d58b9bea85a04e142aca1847f12f77f5a2b1800dc377b68e6ccf5bbe1157c3dd"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:d1931c87f8b125082bf62e26afda07ada182526b"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:57e3fdbfefc875e50a7aa2ba45cd234e4b9c3b730b637ee45f651b38fd2bd2ad"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-x86_64-linux-gnu.tar.gz"
[[builds]]
name = "LinuxKernelHeaders"
platform = "i686-linux-gnu"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:7e2ee7008a5167eda3382b2e47f97e1293625cff"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:c0080cc2caa1e8941af3927558544d8ce6fee146db754a7853fd9d7f58206315"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-i686-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:cf995aeaa611f027abc66f8f103fb957d7b46c7e"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:f8d3075e5380127b81c77561aff3da461efef92a6d713d1c9aee9074c084be56"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-i686-linux-gnu.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:d1931c87f8b125082bf62e26afda07ada182526b"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:57e3fdbfefc875e50a7aa2ba45cd234e4b9c3b730b637ee45f651b38fd2bd2ad"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-i686-linux-gnu.tar.gz"
[[builds]]
name = "LinuxKernelHeaders"
platform = "armv7l-linux-gnueabihf"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:1b464adfbf5169735af8be8e32a5079d2d28f16e"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6923abf5b5e2764db75e33e48491a32afa44f152d424c0cb9a875ac05d327f55"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b9f268eb65a40f21cb6012c5e8116bcf762b2dea"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:414bc1707d6610b1f05cdaa633f084d816e4489c8ea69a578f70ae55b970e4bd"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-armv7l-linux-gnueabihf.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:11985d052b17aac422c79870b27f35b321f35bc1"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1771aa01580b8805282f33fe83be10cde437ae399c24c181dbddbd21372d919f"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-armv7l-linux-gnueabihf.tar.gz"
[[builds]]
name = "LinuxKernelHeaders"
platform = "armv6l-linux-gnueabihf"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:ae2828ba85a9c88254da59141f8f6938f8dcb2bc"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:779c8e823f50d5e967259d0558cde727cb0143eaefdea69d5f58f6601242ba86"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:afc8181dfbb200cb8cab867c5a85dca7e9de8426"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:2e848969b4c0968121af88fea2d83b0ac7d3fb95df855b11998c17ebd0c4499f"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-armv6l-linux-gnueabihf.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:11985d052b17aac422c79870b27f35b321f35bc1"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1771aa01580b8805282f33fe83be10cde437ae399c24c181dbddbd21372d919f"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-armv6l-linux-gnueabihf.tar.gz"
[[builds]]
name = "LinuxKernelHeaders"
platform = "aarch64-linux-gnu"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:75df707947aa7186d9eef45ee8eb4460a7f85f17"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:a959649fe3e7a990ab88f8e9e936dd7797b1df8a0c42cdbcf4c3aa6b6eb2d061"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:186062dfee800826faad9869e73cd355577580a7"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:91abdf857f4e5c90b018a9955326e355297092849677d546823b37d195b97a5b"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:e09615da5544ab54695942c9d97c90355ed006c2"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:58b6e135b7bf92b6ccb87fe430e5d0de0358d9c0acff925a18753407254f9a2f"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-aarch64-linux-gnu.tar.gz"
[[builds]]
name = "LinuxKernelHeaders"
platform = "powerpc64le-linux-gnu"
deps = []
lazy = "false"
src_version = "6.9.5"

    [[builds.licenses]]
    license_text = "The Linux Kernel is provided under:\n\n\tSPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note\n\nBeing under the terms of the GNU General Public License version 2 only,\naccording with:\n\n\tLICENSES/preferred/GPL-2.0\n\nWith an explicit syscall exception, as stated at:\n\n\tLICENSES/exceptions/Linux-syscall-note\n\nIn addition, other licenses may also apply. Please see:\n\n\tDocumentation/process/license-rules.rst\n\nfor more details.\n\nAll contributions to the Linux Kernel are subject to this COPYING file.\n"
    filename = "COPYING"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:6a7c6bbeb3f1923b5fa56109f07cb58a384b088a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:258db463eb03a6fd6ac4ca07ece988fadb4edc5c8e047f020d8516908386d22c"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-build_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:80332753f06511d73bc68a0621235d2bbf82d7cc"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c87ad35be4f7d7a6538d176a51280e3f3371618dfb092633b9aea8f4bc133ac1"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-extract_log-v6.9.0-powerpc64le-linux-gnu.tar.gz"

    [[builds.products]]
    name = "limits_h"
    type = "file"
    path = "include/linux/limits.h"

    [[builds.sources]]
    treehash = "sha1:2d19bcfa9d63170d84b1d52cf1f02a5e7e224aa3"
    url = "https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.9.5.tar.xz"

    [builds.artifact]
    treehash = "sha1:608902a3980fcc42b8c3c0de2b59e6f6991fa681"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:137eeb56bc77f0378cb7080101444ae55a467eff8e6fa93535cff0c203e57ec3"
        url = "https://github.com/staticfloat/LinuxKernelHeaders_jll.jl/releases/download/v6.9.0-GCC/LinuxKernelHeaders-v6.9.0-powerpc64le-linux-gnu.tar.gz"
