# Autogenerated wrapper script for LinuxKernelHeaders_jll for x86_64-linux-musl-target_os+linux-target_arch+aarch64
JLLWrappers.@generate_wrapper_header("LinuxKernelHeaders")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
